name: CI/CD

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.editorconfig'
    branches:
      - main # CI (pr validation)
  push:
    paths-ignore:
      - 'README.md'
      - '.editorconfig'
    branches:
      - main # CI (ci package)
    tags:
      - v*     # CD (release package)

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.404'
        source-url: https://nuget.pkg.github.com/marcusturewicz/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: dotnet build src/Result -c Release
    - run: dotnet test tests/Result.Tests -c Release --no-build
    - run: dotnet pack src/Result -c Release --no-build
    - run: dotnet nuget push src/Result/bin/Release/*.nupkg
      if: github.event_name == 'push' && startswith(github.ref, 'refs/heads')
    - run: dotnet nuget push src/Result/bin/Release/*.nupkg -k ${{secrets.NUGET_ORG_API_KEY}} -s https://api.nuget.org/v3/index.json
      if: github.event_name == 'push' && startswith(github.ref, 'refs/tags')
